### PR TITLE
feat: add patterns for argo addon management

### PR DESCRIPTION
**Pull request by starchx**
*Issue #, if available:*

*Description of changes:*

Added two patterns for ArgoCD addon management.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by starchx** [comment]
CI is failing because the depending feature is not released: https://github.com/aws-quickstart/cdk-eks-blueprints/pull/588

**Comment by starchx** [comment]
@shapirov103 This PR added two patterns as examples of using GitOps addons.

**Review by shapirov103 — COMMENTED** [review]
@starchx looks great as far as code. I do want to have some GTM component for this as well. Let's add the pattern description to the documentation README.md and under docs/patterns. We will be converting it to mkdocs and publish on gh pages soon.

I am running validations on both patterns now.

**Comment by elamaran11** [comment]
@starchx There is no traction on this PR for 9 months now. Could you please work on this if this feature is still needed.?

**Comment by elamaran11** [comment]
@starchx There is no traction on this PR for 9 months now. Could you please work on this if this feature is still needed.?

**Pull request closed without merging**
