### PR TITLE
Blueprints and Kubeflow Pattern Upgrade

### PR DESCRIPTION
**Pull request by elamaran11**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by elamaran11** [comment]
Merge is blocked until this issue on Partner Addon is fixed. https://github.com/aws-quickstart/cdk-eks-blueprints/issues/973
@shapirov103 FYI

**Review by shapirov103 — APPROVED** [review]
LGTM, great work!

**Pull request merged**
