### PR TITLE
uprev aws credentials github action and upgrade to use the latest blu…

### PR DESCRIPTION
**Pull request by shapirov103**
…eprints framework

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — APPROVED** [review]
LGTM

**Comment by elamaran11** [comment]
@shapirov103 Blueprints upgrade is taken care, do we need this PR?

**Comment by elamaran11** [comment]
@shapirov103 Is this PR needed anymore?

**Comment by shapirov103** [comment]
@elamaran11 I must hhave prepared the PR and forgot to merge. The change in the github action seems to be relevant, the rest of the PR is stale. Let's keep it, I will review and resubmit after merging main.

**Comment by shapirov103** [comment]
@elamaran11 please review when you get a chance, it is now in a mergeable state. If it works out here, you can take these changes to the CDK Observability repo as well.

**Review by elamaran11 — APPROVED** [review]
LGTM

**Pull request merged**
